# Generated by Django 3.1.7 on 2021-02-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('azure_key', models.CharField(max_length=100)),
                ('azure_end', models.CharField(max_length=100)),
                ('wit_key', models.CharField(max_length=100)),
                ('weather_key', models.CharField(max_length=100)),
                ('bridge_ip', models.CharField(max_length=100)),
            ],
        ),
    ]
