# Generated by Django 3.1.7 on 2021-02-24 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210222_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='homedata',
            name='voice_gender',
            field=models.CharField(choices=[('M', 'Muž'), ('F', 'Žena')], default='M', max_length=2),
        ),
    ]
